### ISSUE TITLE
Presentation: Process part 1

### ISSUE THREAD

**Issue by ianaack** [bootcampProjectOneTeamFour/food-finder#39]
What were the technologies used?
How were tasks and roles broken down and assigned?

**Comment by mdubb23** [comment]
We used the Yelp Fusion API because as a team we decided this provided us with the exact data that we needed to use for web application 

The other API we used was the google maps directions API we used this so the user could have directions to the restaurant of their choice

We used a basic html structure to hold all of our CSS styling with Tailwind CSS. We used Tailwind CSS to design our application because it had everything we needed to use, and saved us a lot of time.

Then finally we used JavaScript to help build out our dynamic elements on the page like the restaurant cards that list the nearby restaurants and the directions map that is generated.

The way we broke down our tasks and roles we figured from day one who was good at what and we had to people that wanted to do the backend and two people that wanted to do the front end and everybody had their own page they worked on and we had another team member help design the application with us.
